<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="nir-shalmon" name="com.rhhh.bolts.HierarchyXLevelSpaceSavingBoltTest" tests="5" failures="0" timestamp="28 Oct 2017 14:38:26 GMT" time="0.037" errors="2">
  <testcase name="cleanupCorrectly" time="0.003" classname="com.rhhh.bolts.HierarchyXLevelSpaceSavingBoltTest"/>
  <testcase name="shouldAckIfTupleIsReceived" time="0.003" classname="com.rhhh.bolts.HierarchyXLevelSpaceSavingBoltTest">
    <error type="org.mockito.exceptions.verification.WantedButNotInvoked" message="
Wanted but not invoked:
outputCollector.ack(
    Mock for Tuple, hashCode: 931496835
);
-&gt; at com.rhhh.bolts.HierarchyXLevelSpaceSavingBoltTest.shouldAckIfTupleIsReceived(HierarchyXLevelSpaceSavingBoltTest.java:49)
Actually, there were zero interactions with this mock.
">
      <![CDATA[Wanted but not invoked:
outputCollector.ack(
    Mock for Tuple, hashCode: 931496835
);
-> at com.rhhh.bolts.HierarchyXLevelSpaceSavingBoltTest.shouldAckIfTupleIsReceived(HierarchyXLevelSpaceSavingBoltTest.java:49)
Actually, there were zero interactions with this mock.

	at com.rhhh.bolts.HierarchyXLevelSpaceSavingBoltTest.shouldAckIfTupleIsReceived(HierarchyXLevelSpaceSavingBoltTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- shouldAckIfTupleIsReceived -->
  <testcase name="parsingCorrectly" time="0.001" classname="com.rhhh.bolts.HierarchyXLevelSpaceSavingBoltTest"/>
  <testcase name="illegalLevelNumber" time="0.000" classname="com.rhhh.bolts.HierarchyXLevelSpaceSavingBoltTest"/>
  <testcase name="CountTupleCorrectly" time="0.030" classname="com.rhhh.bolts.HierarchyXLevelSpaceSavingBoltTest">
    <error type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at com.rhhh.bolts.HierarchyXLevelSpaceSavingBoltTest.CountTupleCorrectly(HierarchyXLevelSpaceSavingBoltTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
    </error>
  </testcase> <!-- CountTupleCorrectly -->
</testsuite> <!-- com.rhhh.bolts.HierarchyXLevelSpaceSavingBoltTest -->
